- &defaults
  category:     AWS, Cloud
  maintainer:   Markus Schirp
  stability:    experimental
  license:      MIT
  github:       mbj/stratosphere

  flags:
    development: &development_flag
      description: Run GHC with development flags
      default: false
      manual: true

  when:
  - condition: flag(development)
    then:
      ghc-options:
      - -Werror
    else:
      ghc-options: -Wwarn

  default-extensions:
  - DataKinds
  - DeriveGeneric
  - DerivingStrategies
  - DerivingVia
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - LambdaCase
  - MultiParamTypeClasses
  - NoFieldSelectors
  - NoImplicitPrelude
  - NumericUnderscores
  - OverloadedLists
  - OverloadedRecordDot
  - OverloadedStrings
  - PolyKinds
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - Strict
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies

  ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wimplicit-prelude
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-local-signatures
  - -Wmissing-signatures
  - -Wmonomorphism-restriction
  - -Wredundant-constraints
  - -fhide-source-paths
  - -funbox-strict-fields
  - -optP-Wno-nonportable-include-path
