name:       stratosphere-gen
version:    0.1.0
synopsis:   stratosphere code generation
maintainer: Markus Schirp

default-extensions:
- DeriveGeneric
- DerivingStrategies
- ExistentialQuantification
- FlexibleInstances
- FunctionalDependencies
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiParamTypeClasses
- NoImplicitPrelude
- OverloadedStrings
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- ViewPatterns

ghc-options:
- -Wall
- -Wcompat
- -Werror
- -Widentities
- -Wimplicit-prelude
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-local-signatures
- -Wmissing-signatures
- -Wmonomorphism-restriction
- -Wredundant-constraints
- -fhide-source-paths
- -funbox-strict-fields
- -optP-Wno-nonportable-include-path

executables:
  stratosphere-gen:
    source-dirs: src
    main: Gen/Main.hs
    ghc-options: -O0 -main-is Gen.Main
    dependencies:
    - base
    - aeson >= 0.11
    - bytestring
    - containers
    - directory
    - extra
    - filepath
    - lens >= 4.5
    - lens-aeson
    - shakespeare
    - system-filepath
    - text >= 1.1
    - text-manipulate
    - unordered-containers
