name: stratosphere-gen
version: "0.1.0"
synopsis: stratosphere code generation
maintainer: Markus Schirp

default-extensions:
  - DeriveGeneric
  - ExistentialQuantification
  - FlexibleInstances
  - FunctionalDependencies
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - OverloadedStrings
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell

executables:
  stratosphere-gen:
    source-dirs: src
    main: Main.hs
    ghc-options: -Wall -O0
    dependencies:
      - base
      - aeson >= 0.11
      - bytestring
      - containers
      - directory
      - extra
      - filepath
      - lens >= 4.5
      - lens-aeson
      - shakespeare
      - system-filepath
      - text >= 1.1
      - text-manipulate
      - unordered-containers
